# Generated by Django 2.2.7 on 2021-02-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20210223_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Sınav Adı'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='url',
            field=models.SlugField(max_length=60, verbose_name='Sınav urlsi '),
        ),
    ]
