# Generated by Django 2.2.7 on 2021-02-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20210223_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='correct_answer',
            field=models.CharField(max_length=10, verbose_name='Correct Answers'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='wrong_answer',
            field=models.CharField(max_length=10, verbose_name='Wrong Answers'),
        ),
    ]
